Nouveau calcul des recrutements
gip-inclusion/pilotage-airflow pull request #175
Opened 2023-10-25 15:11 UTC by laurinehu

**Carte Notion : ** https://www.notion.so/plateforme-inclusion/TB118-ReCr-er-des-indicateurs-recrutements-tels-que-d-finis-dans-l-ancien-TB-donn-es-de-l-IAE-e2b6a58266594154b976b59e5651a157?pvs=4

### Pourquoi ?

Nouveau mode de calcul des recrutements en suivant les règles de calcul de l'ASP

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2023-10-25 15:12 UTC, laurinehu commented
ToDo : ajout des propriétés structures (localisation etc) et employé (genre etc)

2023-10-30 10:46 UTC, YannickPassa commented on dbt/models/staging/properties.yml
> -      Vue créée pour récupérer les id uniques des salarié(e)s ainsi que leur genre afin de permettre le calcul des ETPs par genre.
J'aurais du rajouter un test qui comparer le nombre de lignes de `stg_salarie` et `salaries_V2`. Est ce quetu pourras le faire stp ? :)

2023-10-30 15:45 UTC, YannickPassa commented on dbt/models/marts/recrutements.sql
> +    split_part(ctr.contrat_mesure_disp_code, '_', 1)                      as type_structure_entree,
Ici je te conseille d'utiliser le seed `ref_mesure_dispositif_asp.csv` pour choper au passage le type de structure des emplois, ptet ça servira un jour

2023-10-30 15:48 UTC, YannickPassa commented on dbt/models/marts/recrutements.sql
> +    app_geo.code_dept                                                     as departement_structure,
pourquoi tu ne prends pas directement le nom_departement de la colonne nom_departement de la table fluxIAE_Structure_v2 ? (pareil pour la région)

2023-10-30 15:48 UTC, YannickPassa commented on dbt/models/marts/recrutements.sql
> +left join {{ source('fluxIAE', 'fluxIAE_Structure') }} as struct
prends autant que possible versions indexed

2023-10-30 15:50 UTC, YannickPassa requested changes
Globalement ok, tu peux utiliser ça pour comparer les chiffres que tu obtiens avec ceux d'Elodie
Mais il manque/il faut modifier des colonnes (localisation en fonction de l'AF, colonnes localisation) et qques petits ajouts

2023-10-31 11:16 UTC, YannickPassa commented on dbt/models/indexed/fluxIAE_Structure_v2.sql
> +    /* l'ASP préconise l'utilisation de l'adresse administrative pour récupérer la commune de la structure */
Tu as bien vérifié que ça donne la même chose que l'ancienne version ?

2023-10-31 11:17 UTC, YannickPassa commented on dbt/models/indexed/recrutements.sql
> +
Ici je pense pas que tu sois obligée de faire des index vu que tu t'en sers nulle part pour des jointures.
TU peux la déplacer dans marts selon moi :)

2023-10-31 11:18 UTC, YannickPassa commented on dbt/models/indexed/recrutements.sql
> +    split_part(ctr.contrat_mesure_disp_code, '_', 1)                      as type_structure_entree,
Tu préfères faire ça que la jointure avec le seed `ref_mesure_dispositif_asp.csv `?

2023-10-31 11:19 UTC, YannickPassa approved these changes
Qques petits points a corriger selon moi mais ça me semble ok

2023-10-31 13:11 UTC, laurinehu commented on dbt/models/indexed/fluxIAE_Structure_v2.sql
> +    /* l'ASP préconise l'utilisation de l'adresse administrative pour récupérer la commune de la structure */
ui !

2023-10-31 13:11 UTC, laurinehu commented on dbt/models/indexed/recrutements.sql
> +    split_part(ctr.contrat_mesure_disp_code, '_', 1)                      as type_structure_entree,
oops non oubli merci !

2023-10-31 14:29 UTC, merged