agregation des reconductions pour calcul des recrutements
gip-inclusion/pilotage-airflow pull request #192
Opened 2023-11-10 21:13 UTC by laurinehu

**Carte Notion : ** 

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2023-11-14 17:53 UTC, rsebille reviewed
Je connais extrêmement mal _pandas_ donc peut-être qu'il fait les choses pas trop idiotement suivant comment on lui demande mais naïvement (bon plus vraiment maintenant...) en _moins pandas_ on arriverais à ce genre de chose :
```python
def get_data(df):
    current_id_pph, datum = None, {}

    # ++ : Ne récupérer de la DB que les colonnes qu'on utilise
    for row in df.sort_values(by=["contrat_id_pph", "contrat_type_contrat"]).itertuples(index=False):
        if row.contrat_id_pph != current_id_pph:
            if datum:
                yield datum  # On "retourne" ce qu'on a calculé
            current_id_pph = row.contrat_id_pph
            datum = {  # ++ Remplacer les dict par des tuples
                "id_ctr_initial": row.contrat_id_ctr,
                "date_embauche": row.contrat_date_embauche,
                "duree_contrats_cumules": 0,
            }

        datum["duree_contrats_cumules"] += row.contrat_duree_contrat
        datum["nombre_reconductions"] = row.contrat_type_contrat
        datum["date_fin_dernier_contrat"] = row.contrat_date_fin_contrat


def model(dbt, session):
    return pd.DataFrame(
        data=get_data(dbt.ref("fluxIAE_ContratMission_v2")),
        columns=[
            "id_ctr_initial",
            "date_embauche",
            "date_fin_dernier_contrat",
            "duree_contrats_cumules",
            "nombre_reconductions",
        ]
    )  # ++ Expliciter les dtypes
```
Le `dbt run` m'indique `Finished running 1 table model in 0 hours 1 minutes and 32.96 seconds (92.96s).` et la mémoire semble rester sous la barre des 5Go, la majorité est dû au 50s de `SELECT` du `dbt.ref()` mais j'ai rien trouvé d'évident pour ne récupérer que les colonnes dont on a besoin et/ou ne pas passer par _pandas_ qui n'est plus vraiment utilisé à la fin.

Les "logiques" d'améliorations de performance :
- Le générateur : permet de traiter au fil de l'eau plutôt que tout d'un coup, ça permet donc surtout d'économiser la mémoire et dans certain cas d'améliorer la vitesse. Le gain sera surement assez faible si la `DataFrame`, ou _dbt_ quand il va la lire, met tout en mémoire mais bon ça coûte pas grand chose à faire ;).
- On n’itère la donnée qu'une seule fois

Changements apportés pour coller aux données car ça cassait :
- Le premier contrat que nous avons n'est pas forcément `contrat_id_pph = 0`
- Il semblerais que `nombre_reconductions` soit en fait `contrat_type_contrat`, donc pas besoin de le recalculer

Remarque :
- Les `++` sont les possibles pistes d'améliorations si l'on souhaitait faire encore mieux.
- On pourrais se passer du tri sur `contrat_type_contrat` en utilisant des `min()`/`max()` pour les champs, ce qui peux être plus explicite.

2023-11-17 12:30 UTC, YannickPassa commented on dbt/models/indexed/sorties_v2.sql
> +    extract(year from ctr.contrat_date_fin_contrat)                              as annee_fin_contrat,
pourquoi tu as changé ça ?

2023-11-17 14:41 UTC, YannickPassa requested changes
ça me semble ok mais il manque :
- La doc
- des tests si pertinent
- des réponses à mes pitites questions

2023-11-17 14:41 UTC, YannickPassa commented on dbt/models/indexed/sorties_v2.sql
> +    extract(year from ctr.contrat_date_fin_contrat)                              as annee_fin_contrat,
Pourquoi tu as changé ici ?

2023-11-17 14:41 UTC, YannickPassa commented on dbt/models/marts/weekly/recrutements.sql
> +    rec.id_derniere_reconduction     as identifiant_derniere_reconduction,
hmm ici le nom de la colonne est trompeur, précise bien qu'on parle d'un id_contrat

2023-11-17 14:41 UTC, YannickPassa commented on dbt/models/staging/stg_recrutements.sql
> +    id_recrutement
c'est normal que id recrutement soit dans le group by mais pas dans le select ?

2023-11-17 14:41 UTC, YannickPassa commented on dbt/models/indexed/sorties_v2.sql
> +    extract(year from ctr.contrat_date_fin_contrat)                              as annee_fin_contrat,
et pas sur la ligne 53 ?

2023-11-17 15:21 UTC, YannickPassa approved these changes
Je valide mais il manque la doc pour indexed et les réponses à mes deux commentaires (moins important)

2023-11-18 09:46 UTC, laurinehu commented
Sorry mes commentaires étaient resté en pending et j'ai oublié de commit le indexed !

2023-11-20 14:04 UTC, merged