Laurinehu/tx couv global
gip-inclusion/pilotage-airflow pull request #230
Opened 2024-01-10 10:12 UTC by laurinehu

**Carte Notion : **

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-01-18 10:18 UTC, YannickPassa requested changes
Qques petites modifs à prendre en compte :)

2024-01-18 10:18 UTC, YannickPassa commented on dbt/models/marts/daily/nb_utilisateurs_potentiels.py
> -    structures = structures[structures["active"] == 1]
pourquoi tu retires les actives ?

2024-01-18 10:18 UTC, YannickPassa commented on dbt/models/marts/weekly/suivi_visites_tous_tb_prive_mensuel.sql
> +    visits.departement                          as "département_num",
Je te propose de laisser "département" et de mettre "nom_département" qd il y a le nom, histoire que ça soit harmonisé avec ce qu'on reçoit du C1.

2024-01-18 10:18 UTC, YannickPassa commented on dbt/models/marts/weekly/taux_couverture_global_mensuel.sql
> +    cast(visites.nb_organisations as float) / cast(potentiel.potentiel as float) as taux_couv
Définis ça en float directement sur tes tables d'origine vu que tu utilises le float sur plusieurs scripts différents.

2024-01-18 10:18 UTC, YannickPassa commented on dbt/models/marts/weekly/suivi_visites_tous_tb_prive_trimestre.sql
> +    on c1_users.id = cast(visits.id_utilisateur as integer)
Définis ça en int directement sur la table d'origine vu que tu utilises l'entier sur plusieurs scripts différents.

2024-01-22 10:08 UTC, YannickPassa commented
Oublie pas de squasher tes commits !

2024-01-22 10:09 UTC, YannickPassa commented on dbt/models/marts/daily/nb_utilisateurs_potentiels.py
> -    structures = structures[structures["active"] == 1]
actives retirées car la définition de structure active est très restrictive

2024-01-22 10:12 UTC, YannickPassa approved these changes
ok pour moi

2024-01-22 10:12 UTC, YannickPassa commented on dbt/models/marts/daily/properties.yml
> +            column_type: float
Tu peux m'expliquer ce que tu as fait ici stp ?

2024-01-22 10:13 UTC, YannickPassa commented
Du coup tu n'as aps défini le taux de couverture et l'id en tant qu'integer sur une premiere table car tu es obligée de les recalculer à chaque fois c'est ça ?

2024-01-23 17:58 UTC, laurinehu commented on dbt/models/marts/daily/properties.yml
> +            column_type: float
c'est pour que la colonne potentiel soit de type float dans cette table directement

2024-01-23 17:58 UTC, laurinehu commented
pas compris ta dernière question ?

2024-01-23 18:04 UTC, merged