Expé Nord France Travail
gip-inclusion/pilotage-airflow pull request #274
Opened 2024-04-05 14:12 UTC by laurinehu

**Carte Notion : **  https://www.notion.so/plateforme-inclusion/Clarifier-FT-exp-rimentation-Nord-et-analyser-ce-qu-on-peut-en-faire-18582886b7c74cc78d3c4b550613f94b?pvs=4

### Pourquoi ?

- Création du dag permettant de charger le jeu de données nettoyé sur la DB
- Création des tables permettant de créer les premiers indicateurs

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-04-08 16:06 UTC, YannickPassa requested changes
Mes remarques !
-Je passerai par un `df.to_sql()`, si tu souhaites quand meme faire une fonction il faut changer le nom de cette dernière
-Je n'utiliserai pas gdrive mais le ftp
-Squash tes commits >:(

2024-04-08 16:06 UTC, YannickPassa commented on dags/ft_expe_nord.py
> +NPS_CREATE_TABLE_SQL = """
Le nom de ta fonction est pas bon, il faut modifier ça et en faire une fonction générique

2024-04-08 16:06 UTC, YannickPassa commented on dags/ft_expe_nord.py
> +NPS_CREATE_TABLE_SQL = """
Sinon remarque plus globale, pourquoi tu veux créer la table et pas faire un` df.to_sql() `?
S'ils rajoutent et/ou modifient des colonnes (les connaissant ça peut arriver) tu vas te retrouver avec un DAG qui est cassé et tu devras tout refaire

2024-04-08 16:06 UTC, YannickPassa commented on dags/ft_expe_nord.py
> +    schedule_interval="@monthly",
on est sur de la récurrence ? sinon tu peux mettre None

2024-04-08 16:06 UTC, YannickPassa commented on dags/ft_expe_nord.py
> +            csv_data_url = Variable.get("FT_EXPE_CSV_DATA_URL")
c pas un peu risqué de mettre un fichier DSN sur google drive (je suppose que c'est là ?) Est ce que ça serait pas mieux de l'héberger sur le ftp ?

2024-04-09 06:34 UTC, laurinehu commented on dags/ft_expe_nord.py
> +            csv_data_url = Variable.get("FT_EXPE_CSV_DATA_URL")
si carrément ! je voulais t'en parler comme j'ai jamais fait mais j'ai oublié.

2024-04-11 12:45 UTC, YannickPassa approved these changes

2024-04-11 12:45 UTC, YannickPassa commented
tu as pu tester le dag en local ?

2024-04-11 13:50 UTC, laurinehu commented
yes j'ai testé en local

2024-04-11 14:01 UTC, merged