Données pour convergence
gip-inclusion/pilotage-airflow pull request #292
Opened 2024-04-29 17:11 UTC by laurinehu

**Carte Notion : **  https://www.notion.so/plateforme-inclusion/Convergence-premiers-pas-ensemble-extraire-donn-es-orientation-des-candidatures-et-dur-e-des-par-723ff163e3e448c188d2298217b73b24?pvs=4

### Pourquoi ?

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-05-03 09:16 UTC, YannickPassa requested changes
Tu peux te passer de la table emi (sauf si contrats a 0h de travail non pris en compte)

2024-05-03 09:16 UTC, YannickPassa commented on dbt/models/marts/oneshot/contrats_convergence_2023.sql
> +from {{ ref("fluxIAE_EtatMensuelIndiv_v2") }} as emi
pourquoi tu utilises cette table qui est énorme et pas ContratMission qui contient aussi la date de fin reelle (date_sortie_definitive) ?
Ca t'éviterait une jointe en +

2024-05-03 09:16 UTC, YannickPassa commented on dbt/models/marts/oneshot/contrats_convergence_2023.sql
> +        when cgv_structs.siret is not null and ctr.contrat_mesure_disp_code = 'ACI_DC' then 'Oui'
pourquoi pas ACI_MP aussi ?

2024-05-03 09:16 UTC, YannickPassa commented on dbt/models/marts/oneshot/contrats_convergence_2023.sql
> +where ctr.contrat_duree_contrat is not null and extract(year from to_date(emi.emi_date_fin_reelle, 'DD-MM-YYYY')) = 2023
Tu as vérifié s'il n'y avait pas des contrats de durée non nulle qui ont 0h de travail ?
S'ils existent est ce que ces contrats sont a prendre en compte ?

2024-05-03 09:16 UTC, YannickPassa commented on dbt/models/marts/oneshot/contrats_convergence_2023.sql
> +where ctr.contrat_duree_contrat is not null and extract(year from to_date(emi.emi_date_fin_reelle, 'DD-MM-YYYY')) = 2023
(dans ce cas la la table EMI redevient pertinente)

2024-05-03 09:38 UTC, laurinehu commented on dbt/models/marts/oneshot/contrats_convergence_2023.sql
> +from {{ ref("fluxIAE_EtatMensuelIndiv_v2") }} as emi
du coup on reste sur emi pour le moment, avec ajout de la colonne nb d'heures pour isoler les candidats à 0h si besoin par cvg (à clarifier pour le moment)

2024-05-03 20:23 UTC, YannickPassa requested changes
Il faut revoir les heures travaillées + faire un ptit make fix :)

2024-05-03 20:23 UTC, YannickPassa commented on dbt/models/marts/oneshot/contrats_convergence_2023.sql
> +    emi.emi_nb_heures_travail as nb_heures,
ça ne va pas marcher, il faut faire une somme.
L'emi c'est une entrée mois par mois des heures réalisées. Il faut que tu sommes toutes les heures associées au même contrat.

2024-05-05 10:30 UTC, laurinehu commented on dbt/models/marts/oneshot/contrats_convergence_2023.sql
> +    emi.emi_nb_heures_travail as nb_heures,
ahhhhh merci !

2024-05-06 11:55 UTC, YannickPassa approved these changes
maintenant c bon !

2024-05-06 14:47 UTC, merged