DAG pour màj des tables convergence
gip-inclusion/pilotage-airflow pull request #300
Opened 2024-05-16 15:53 UTC by laurinehu

**Carte Notion : **

### Pourquoi ?

Pour pouvoir mettre à jour les tables convergence ponctuellement :)

### Checks

- [x] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [x] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-05-21 16:40 UTC, YannickPassa commented on dags/dbt_convergence.py
> +        bash_command="dbt run -s candidatures_convergence contrats_convergence_2023 }}",
pourquoi tu n'ajoutes pas plutot une condition dans un dag qui existe deja ?

2024-05-21 16:42 UTC, YannickPassa requested changes
Plutot que créer un dag, rajoute une condition sur les dag deja existant
Vu que les données proviennent du fluxIAE, plutot dans dbt_weekly

2024-05-29 09:40 UTC, YannickPassa commented on dags/dbt_weekly.py
> +                kwargs["ti"].xcom_push(
@laurinehu t'as pu tester correctement du coup ?

2024-05-29 15:56 UTC, laurinehu commented
je sais pas pourquoi il redemandait une relecture alors que c'était tout bon !!

2024-06-05 10:06 UTC, YannickPassa approved these changes
A priori c passé pour moi, go

2024-06-05 10:10 UTC, merged