Modification de la table utilisateurs et ajout de nouveaux champs
gip-inclusion/pilotage-airflow pull request #308
Opened 2024-05-29 15:27 UTC by laurinehu

**Carte Notion : ** 

https://www.notion.so/gip-inclusion/Rajouter-nom-et-pr-nom-dans-table-utilisateurs-ac2d88962fb84b30b7f027c4ae2a8f2f?pvs=4
https://www.notion.so/gip-inclusion/Faire-correspondre-table-utilisateurs-C2-et-base-emplois-sur-la-structure-ajout-de-l-id-structure-fa367ff48deb4b50a3ca63b8ac453193?pvs=4

### Pourquoi ?

Ajout des champs nom et prénom
Ajout du champs id structure/institution/orga

### Checks

- [x] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-05-29 15:54 UTC, laurinehu commented
J'ai laissé en deux commits pour que ce soit plus simmple à relire vu les 250mille modifs, je squash après

2024-06-06 13:19 UTC, YannickPassa commented on dbt/models/marts/daily/utilisateurs.sql
> +from {{ source('emplois', 'utilisateurs_v0') }} as utilisateurs
Il faut rajouter un test pour vérifier que utilisateurs_v0 = utilisateurs

2024-06-06 13:20 UTC, YannickPassa requested changes
Test à rajouter puis staging a clarifier :)

2024-06-06 14:01 UTC, laurinehu commented
j'ai supprimé la staging qui n'avait rien à faire là (oops)

2024-06-06 15:49 UTC, merged