Table taux_refus_siae : renommer et ajouter des agrégations
gip-inclusion/pilotage-airflow pull request #322
Opened 2024-06-20 09:32 UTC by laurinehu

**Carte Notion : ** https://www.notion.so/gip-inclusion/Filtre-et-variable-Indicateur-taux-de-refus-du-TB116-r-alis-sur-une-table-qui-ne-permet-pas-d-ut-07b73cc17542471b8b52a970aadb0afb?pvs=4

### Pourquoi ?

Renommer : pour qu'on ait des `taux` partout et pas de `tx` ;p un seul indicateur calculé sur cette table, donc c'est pas chiant de le refaire (sinon j'aurais pas fait)
Agréger : pour permettre de brancher les filtres sur le tb116 (cf carte)

J'en profite pour déplacer le modèle dans marts.

### Checks

- [x] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [x] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-06-20 12:22 UTC, YannickPassa commented on dbt/models/marts/daily/taux_refus_siae.sql
>      etp_conventionnes.nombre_etp_conventionnes,
Alors ça il faut absolument le retirer c'est complètement faux et on a aps trop le droit de l'afficher

2024-06-20 12:22 UTC, YannickPassa commented on dbt/models/marts/daily/taux_refus_siae.sql
>      etp_conventionnes.nombre_etp_conventionnes,
je savais pas du tout que c'etait la !!

2024-06-20 12:23 UTC, YannickPassa requested changes
Il faut retirer tout ce qui concerne les etps !

2024-06-20 14:42 UTC, laurinehu commented on dbt/models/marts/daily/taux_refus_siae.sql
>      etp_conventionnes.nombre_etp_conventionnes,
c'est pas du tout utilisé et affiché, je pensais que tu utilisais ça de ton côté pour je ne sais quel besoin

2024-06-24 10:18 UTC, YannickPassa approved these changes
Ok ! faudra juste verifier que ça casse pas l'indicateur

2024-06-24 10:25 UTC, merged