Table pour le calcul d'indicateurs mensuels des candidats en recherche active
gip-inclusion/pilotage-airflow pull request #347
Opened 2024-08-21 16:57 UTC by laurinehu

**Carte Notion : **

### Pourquoi ?

Pour permettre l'historisation des indicateurs de candidats en recherche active.

### Checks

- [x] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [x] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-08-21 17:01 UTC, laurinehu commented
à discuter : 
- vue mensuelle car une vue hebdo serait trop grosse (de 1M à 4M de lignes environ) -> une autre solution est de calculer directement les indicateurs agrégés pour avoir moins de lignes
- pourquoi est-ce qu'on backup toutes les colonnes dans le snapshot des candidats en recherche active ? on pourrait ne garder que les colonnes qui changent et l'id du candidat (gain de place) et passer par une jointure ensuite pour récupérer les caractéristiques du candidat
- ces tables sont déjà grandes et vont viiiiite grandir, il faut qu'on voit ensemble ce qu'on met en place pour économiser de la place avant que tout explose.

2024-08-22 09:05 UTC, rsebille reviewed
Je met mes réflexions avant de les oublier :grin:.

_tl;dr_ : A mon sens c'est un questionnement philosophique qu'il faut avoir, une fois celui-ci répondu la technique sera évidente et suivra tout naturellement.

> vue mensuelle car une vue hebdo serait trop grosse (de 1M à 4M de lignes environ)

La granularité dépend du besoin, si mensuel est suffisant alors mensuel sinon plus fin et on optimisera [1] si nécessaire : _premature optimization is the root of all evil_.
Et vu qu'on pourra changer de granularité quand on veux car la donnée est gardée dans le _snapshot_ il n'y a pas trop de problème à commencer par mensuel pour changer ensuite.

> pourquoi est-ce qu'on backup toutes les colonnes dans le snapshot des candidats en recherche active ? on pourrait ne garder que les colonnes qui changent et l'id du candidat (gain de place) et passer par une jointure ensuite pour récupérer les caractéristiques du candidat

Là y a 2 écoles, les 2 sont valides et dépendent de ce que vous envisager d'avoir besoin :
1. _snapshot_ de toute les données car on veux pouvoir faire un nouvel indicateur dans x temps et donc profiter de tout l'historique. => Ça prend (beaucoup) plus de place mais en contrepartie ça permet de tout faire n'importe quand.
2. _snapshot_ uniquement les colonnes avec la donnée qui nous intéresse. => Moins de place, et besoin de temps pour créer l'historique après l'ajout d'un nouvel indicateur

> ces tables sont déjà grandes et vont viiiiite grandir, il faut qu'on voit ensemble ce qu'on met en place pour économiser de la place avant que tout explose.

Même type de réponse :), quel est le besoin actuel et anticipé ?
Si on veux tout l'historique alors pas le choix, si en fait on veux que les X derniers temps alors on peux limiter la donnée utilisée, soit depuis les sources soit de notre coté.

---

[1] Le nombre de ligne est assez peu important et de toute manière on s'attend a avoir de grosse tables, par contre faudra effectivement avoir une discipline de ne prendre que ce dont on aurais besoin et d'utiliser des types de colonnes appropriées.

2024-09-11 12:42 UTC, YannickPassa requested changes
Qques petits changements.
Tu as vérifié avec un fichier test que ton modèle incrémental marchait correctement ?

2024-09-11 12:42 UTC, YannickPassa commented on dbt/models/marts/daily/properties.yml
> +  - name: candidats_recherche_active_histo
Pourquoi c dans daily pour les properties et weekly pour le script ?

2024-09-11 12:42 UTC, YannickPassa commented on dbt/models/marts/weekly/candidats_recherche_active_histo.sql
> +    ) as week_series
On est d'accord que tu veux bien du hebdo (le titre de ta PR dit mensuel) ?

2024-09-11 12:48 UTC, rsebille commented on dbt/models/marts/weekly/candidats_recherche_active_histo.sql
> +or dbt_valid_to > date_trunc('week', current_date) - interval '1 week'
J'ai pas testé donc je vais peut-être dire de la merde mais je pense qu'on va avoir des problèmes :).

Mise à jour des lignes existantes
---

Si tu veux des `UPDATE` il faut donner une [unique key](https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional) (un truc du genre `["id", "semaine_valide"]`) sinon les lignes qui se ferment vont être dupliquée, on aura celles enregistrées alors qu'elle était ouverte puis celle au moment de la fermeture, et d'ailleurs je pense que les lignes des lignes ouvertes vont aussi être dupliquée mais à chaque lancement pour celles-ci, et je me demande ce qui va se passer quand on a plusieurs lignes pour la même semaine :thinking:.

Clause incrémentale
---

Il faut plutôt utiliser la dernière valeur connue dans la table que `current_date`, sinon on va avoir des trucs chelou en fonction de quand (et si) on lance le modèle. En gros ici tu supposes que le modèle va être lancer exactement 1 fois toutes les semaines au même moment, ce qui ne sera jamais vraiment le cas.
Et pour un peu les mêmes raisons il faut sûrement plutôt utiliser `>=` que `>` pour ne pas rater les lignes qui se ferment et s'ouvrent pendant une semaine déjà connue.

2024-09-11 12:48 UTC, rsebille commented on dbt/models/marts/weekly/candidats_recherche_active_histo.sql
> +        -- so we compute row for each month from valid_to to today
```suggestion
        -- so we compute row for each week from valid_to to today
```

2024-09-11 12:48 UTC, rsebille commented on dbt/models/marts/weekly/candidats_recherche_active_histo.sql
> +        end,
```suggestion
        date_trunc('week', coalesce(dbt_valid_to, current_date)),
```
Non ?

2024-10-09 09:21 UTC, laurinehu commented on dbt/models/marts/daily/properties.yml
> +  - name: candidats_recherche_active_histo
oopsie erreur, je le bouge dans weekly

2024-12-18 10:16 UTC, closed without merging