Ajout d'un script oneshot pour extraction candidatures Manche
gip-inclusion/pilotage-airflow pull request #362
Opened 2024-10-17 15:36 UTC by JulesLXI

**Carte Notion : **

### Pourquoi ?

Demande de la DDETS 50 d'avoir une extraction de candidatures agrégées pour les 6 premiers mois de 2024

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-10-18 05:45 UTC, YannickPassa requested changes
J'ai aussi ajouté a ta PR les epci des structures. Tu peux les rajouter dans la table !
Ca te fera un bon exercice de récupérer mon commit, de rajouter un commit avec les modif puis de squash le commit 3 avec le commit 1 :)

2024-10-18 05:45 UTC, YannickPassa commented on dbt/models/marts/oneshot/candidatures_ddets50.sql
> +    count(cel.id)                                                                                                    as "Nombre de candidatures"
En vrai vu qu'on respecte nulle part le secret stat, je retirerai ça et je mettrai une ligne = 1 candidature.

2024-10-18 05:45 UTC, YannickPassa commented on dbt/models/marts/oneshot/candidatures_ddets50.sql
> +    date_part('month', cel.date_candidature)                                                                         as "Mois de l'année 2024",
Vu qu'on va passer sur une ligne = 1 candidature tu peux juste mettre la date de candidature et zou

2024-10-18 05:45 UTC, YannickPassa commented on dbt/models/marts/oneshot/candidatures_ddets50.sql
> +    case when cel."état" = 'Candidature acceptée' then 'oui' else 'non' end                                          as "Candidature acceptée",
Ici aussi, tu peux fusionner les 3 colonnes et en faire qu'une
```
case 
when cel."état" = 'Candidature acceptée' then 'Candidature acceptée'
when cel."état" = 'Candidature refusée' then 'Candidature refusée'
else 'Candidature en cours ou embauché ailleurs
end as "etat de la candidature"
```

2024-10-20 16:08 UTC, laurinehu commented on dbt/models/marts/oneshot/candidatures_ddets50.sql
> +    count(cel.id)                                                                                                    as "Nombre de candidatures"
je trouve pas la carte / historique de la demande mais je pense que ça les aide d avoir la donnée agrégée non ?

2024-10-20 16:21 UTC, laurinehu approved these changes
lgtm, modulo une ligne vide à enlever + epci de yannick

2024-10-20 16:21 UTC, laurinehu commented on dbt/models/marts/oneshot/candidatures_ddets50.sql
> +
ligne vide à virer (il râle pas le linter ? :o )

2024-10-20 16:21 UTC, laurinehu commented on dbt/models/marts/oneshot/candidatures_ddets50.sql
> +    count(cel.id)                                                                                                    as "Nombre de candidatures"
perso je laisserais comme ça mtn que c'est fait et propre, surtout si ça leur éviter de re-traiter derrieèer

2024-10-20 16:53 UTC, YannickPassa commented on dbt/models/marts/oneshot/candidatures_ddets50.sql
> +    count(cel.id)                                                                                                    as "Nombre de candidatures"
En fait le truc, c'est que la c'est tellement spécifique que t'as 97% qui est non agrégé, donc au final tu perds de l'info en faisant comme ça.

2024-10-22 15:16 UTC, YannickPassa approved these changes
:mount_fuji:

2024-10-22 15:19 UTC, merged