Dag pour refresh les oneshot
gip-inclusion/pilotage-airflow pull request #364
Opened 2024-10-24 13:35 UTC by JulesLXI

**Carte Notion : **

### Pourquoi ?

Création d'un dag pour pouvoir refresh les fichiers 'oneshot' sans refresh le reste

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-10-25 10:06 UTC, YannickPassa requested changes
On ne veut pas de condition particulière pour ce DAG, ton dbt run lancera que les oneshot. Donc pas besoin de la fonction params_check :)

2024-10-25 10:06 UTC, YannickPassa commented on dags/dbt_oneshot.py
> +    def params_check(params=None, **kwargs):
Ici tu n'as pas besoin de mettre des conditions on veut juste le refresh des oneshot donc tu n'as pas besoin de cette fonction

2024-10-25 10:06 UTC, YannickPassa commented on dags/dbt_oneshot.py
> +        bash_command="dbt seed {{ ti.xcom_pull(task_ids='params_check', key='dbt_seed_args') }}",
ici ça sera 
`bash_command="dbt seed",`

2024-10-25 10:06 UTC, YannickPassa commented on dags/dbt_oneshot.py
> +        bash_command="dbt seed {{ ti.xcom_pull(task_ids='params_check', key='dbt_seed_args') }}",
@laurinehu je me demande si on ferait pas un` dbt seed --full-refresh`, il se peut que les oneshot soient accompagnés de seed particulières et sans le refresh ça risque de pas bien les prendre en compte. Je suis preneur de ton avis !

2024-10-25 10:06 UTC, YannickPassa commented on dags/dbt_oneshot.py
> +        bash_command="dbt run {{ ti.xcom_pull(task_ids='params_check', key='dbt_run_args') }}",
pareil qu'au dessus 
`bash_command="dbt run --select marts.oneshot",`

2024-10-29 10:29 UTC, laurinehu commented on dags/dbt_oneshot.py
> +        bash_command="dbt seed {{ ti.xcom_pull(task_ids='params_check', key='dbt_seed_args') }}",
on pourrait rendre le lancement facultatif ! j'ai l'impression que ds la majuer partie des cas on n'en a pas besoin

```
run_dbt_seed = Variable.get("run_dbt_seed", default_var="false")

dbt_seed = bash.BashOperator(
    task_id="dbt_seed",
    bash_command="dbt seed --full-refresh",
    env=env_vars,
    append_env=True,
) if run_dbt_seed else None
    ```
    
    wdyt?

2024-10-29 10:31 UTC, laurinehu commented on dags/dbt_oneshot.py
> +        bash_command="dbt seed {{ ti.xcom_pull(task_ids='params_check', key='dbt_seed_args') }}",
et je donnerais bien aussi en paramètre le nom du modèle à lancer ds oneshot pour éviter de tout relancer si y'a pas besoin. par exemple : 

```
model_name = Variable.get("dbt_model_name", default_var="marts.oneshot")

dbt_run = bash.BashOperator(
    task_id="dbt_run",
    bash_command=f"dbt run --select {model_name}",
    env=env_vars,
    append_env=True,
)```

2024-10-29 10:31 UTC, laurinehu commented on dags/dbt_oneshot.py
> +        bash_command="dbt seed {{ ti.xcom_pull(task_ids='params_check', key='dbt_seed_args') }}",
@JulesLXI @YannickPassa wdyt?

2024-10-29 10:39 UTC, YannickPassa commented on dags/dbt_oneshot.py
> +        bash_command="dbt seed {{ ti.xcom_pull(task_ids='params_check', key='dbt_seed_args') }}",
Du coup dans ton interface Airflow tu pourras retrouver le modele a lancer ?

2024-10-29 11:01 UTC, YannickPassa approved these changes
Ok Jules !
On prendra en compte les suggestions de Laurine une autre fois, c'est un peu + complexe comme dev

2024-10-29 11:03 UTC, JulesLXI commented on dags/dbt_oneshot.py
> +        bash_command="dbt seed {{ ti.xcom_pull(task_ids='params_check', key='dbt_seed_args') }}",
Ah yes c'est super intéressant, je garde en tête pour la prochaine fois

2024-10-29 11:06 UTC, merged