Ajout d'un + pour le calcul des tables dépendantes
gip-inclusion/pilotage-airflow pull request #365
Opened 2024-10-29 13:18 UTC by laurinehu

**Carte Notion : **

### Pourquoi ?

Sinon ça plante sur les stg manquantes

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2024-10-29 13:38 UTC, JulesLXI approved these changes
Merci!

2024-10-29 15:21 UTC, YannickPassa requested changes
Je pense qu'on est mieux sans le + et avec staging

2024-10-29 15:21 UTC, YannickPassa commented on dags/dbt_oneshot.py
> -        bash_command="dbt run --select marts.oneshot",
En fait le problème la c que ça va créer toutes les tables et dépendances liées au oneshot. Donc par exemple ça calcule sorties_v2 qui prend des plombes a tourner. C'est mieux de faire `dbt run --select staging marts.oneshort`

2024-11-23 09:15 UTC, YannickPassa approved these changes

2024-11-23 09:18 UTC, merged