Stats suivi utilisateurs tbs
gip-inclusion/pilotage-airflow pull request #51
Opened 2023-05-30 12:58 UTC by laurinehu

**Carte Notion : ** https://www.notion.so/plateforme-inclusion/R-aliser-table-s-permettant-de-calculer-des-indicateurs-d-impact-suivre-sur-le-produit-4894e065aba34b04b8b1d9295e5d5a53?pvs=4

### Pourquoi ?

Produire des tables de suivi utilisateur pour Annie à partir de la table de suivi matomo 

### Checks

- [x] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [x] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2023-05-30 13:19 UTC, vperron commented on dbt/models/_sources.yml
> +      - name: c1_private_dashboard_visits_v0
techniquement cette table a en fait presque plus sa place dans les sources "emplois" car ces données ne sont pas extraites de matomo mais directement via du code dans les emplois.

2023-05-30 13:19 UTC, vperron commented on dbt/seeds/metabase_tb_ids.csv
> +"tb 160 - Facilitation de l'embauche DREETS/DDETS",160
je chipote mais traditionnellement on met l'ID en première colonne puis le nom en second, et on trie par ID, c'est beaucoup plus lisible. Non ?

2023-05-30 13:19 UTC, vperron commented on dbt/seeds/properties.yml
> +  - name: metabase_tb_ids
`metabase_dashboards` ?

2023-05-30 13:19 UTC, vperron commented on dbt/models/marts/suivi_utilisateurs_tb_prive_semaine.sql
> +    count(distinct visits.measured_at)    as nb_visits
je suis un peu gêné par l'alternance de choix parfois contradictoires anglais/français (tb versus dashboard, visits vs semaine, etc etc. Ce serait cool de s'entendre sur une vraie convention non ? Surtout dans les marts ?

2023-05-30 13:19 UTC, vperron commented on dbt/models/marts/suivi_utilisateurs_tb_prive_semaine.sql
> +    date_part('week', visits.measured_at)
on peut/veut utiliser l'alias ? ca éviterait la duplication de `date_part` peut-être.

2023-05-30 14:16 UTC, YannickPassa commented on dbt/models/marts/suivi_utilisateurs_tb_prive_semaine.sql
> +    visits.user_id                        as id_utilisateur,
Je pense qu'il faudrait rajouter l'id de la SIAE/organisation/institution ça nous permettra de faire des jointures dans le futur et d'avoir les noms des SIAE/organisation/institution qui reviennent.

2023-05-30 14:17 UTC, YannickPassa commented on dbt/models/marts/suivi_tb_prive_semaine.sql
> +            when nb_visits > 1 then 1
Ici si j'ai bien compris tu sais s'il est revenu plus d'une fois, mais est ce que tu sais combien de fois il est revenu ?

2023-05-30 14:22 UTC, YannickPassa requested changes
Une colonne donnant l'info de la SIAE/organisation/institution d'ou proviennent les visiteurs manque, selon moi.

Tu peux faire ça facilement via les tables `structures`, `organisations` et `institutions`

Sinon, pour la convention dans marts : pour moi on met toujours du français (ça nous évite de changer les noms des colonnes lorsqu'on fait des tables) cc @dejafait @vperron

2023-05-30 14:28 UTC, laurinehu commented on dbt/models/marts/suivi_tb_prive_semaine.sql
> +            when nb_visits > 1 then 1
sur cette table, je sais simplement que N visiteurs sont revenus plusieurs fois sur un tb sur une semaine. 
pour le nb de visites hebdo d'un utilisateur sur un tb, c'est sur la table `suivi_utilisateur_tb_prive_semaine`
par contre je peux ajouter sur cette table le nb moyen de visites hebdo pour un tb et une semaine.

2023-05-30 14:32 UTC, YannickPassa commented on dbt/models/marts/suivi_tb_prive_semaine.sql
> +            when nb_visits > 1 then 1
Ah oui pardon j'avais pas vu sur l'autre table pardon !

Je pense que c'est bien d'ajouter l'info nombre de visites hebdo pour un tb et une semaine par utilisateur sur cette table qui est dans `marts` (mais pas le nombre moyen)

On fera la moyenne sur metabase derrière

2023-06-05 10:33 UTC, YannickPassa approved these changes
Ok apres discussion avec Laurine

2023-06-05 11:37 UTC, merged