Création d'un DAG calculant le NPS du pilotage
gip-inclusion/pilotage-airflow pull request #63
Opened 2023-06-08 09:44 UTC by YannickPassa

### Pourquoi ?

Le NPS du pilotage est actuellement calculé à la main (pas bien). Ce DAG a pour but d'automatiser ce processus.

### Checks

- [ ] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [ ] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [ ] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2023-06-09 09:31 UTC, vperron requested changes
On pourrait essayer de se prendre 10 minutes pour que je parle de certaines spécificités airflow et bien comprendre ce qu'on veut faire ! Bon début !

2023-06-09 09:31 UTC, vperron commented on dags/common/dates.py
> +end_of_previous_week = start_of_week - timedelta(days=1)  # End of the previous week
nope, ça ne fonctionnera pas. Cette façon de faire stockera `today` au moment où tu mets en prod mais ne le mettra pas à jour le lendemain. Il faut que tu fasses des fonctions qui recalculent ça à chaque appel.

Sur une autre note, les commentaires sont inutiles, les noms des variables suffisent (et doivent suffire, si tu dois expliquer par un commentaire ce que fait le code c'est qu'il n'est pas clair ou mal nommé)

Je l'ai déjà dit quelque part mais les commentaires (la doc aussi)  doivent décrire des choses pas évidentes ou le pourquoi d'une décision, etc.

Pour le reste, bien nommer les choses est plus important. Là ca fait redite et pose le souci de la "moisissure" des commentaires: si tu renommes/modifie ta variable, en général on oublie de MAJ le commentaire avec et il devient carrément trompeur.

2023-06-09 09:31 UTC, vperron commented on dags/nps_pilotage.py
> +        for name, pub_sheet_url in Variable.get("NPS_DASHBOARD_PILOTAGE", deserialize_json=True):
on a plusieurs google sheets contenant les résultat de différents NPS ?

2023-06-09 09:31 UTC, vperron commented on dags/nps_pilotage.py
> +        for col in colonnes:
toutes les variables sont en anglais dans le code, restons consistant. 

Et je ne comprends pas bien pourquoi on les met à `NaN` ? Là, un commentaire serait utile pour décrire le "pourquoi" ^^

2023-06-09 09:31 UTC, vperron commented on dags/nps_pilotage.py
> +                "Date",
tu te répètes alors que tu as déjà les noms de ces colonnes ailleurs, réutilise toujours au maximum. Sinon un jour tu modifieras le nom en haut et pas en bas et tu auras un crash.

2023-06-09 09:31 UTC, vperron commented on dags/nps_pilotage.py
> +        engine = create_engine(url)
faudrait peut-être créer un helper à force qui prend user, pass, host, port, db et qui retourne un engine. On a déjà ça d'ans d'autres DAGs.

2023-06-11 13:29 UTC, YannickPassa commented on dags/nps_pilotage.py
> +        for name, pub_sheet_url in Variable.get("NPS_DASHBOARD_PILOTAGE", deserialize_json=True):
oui ! faut que je les ajoute à la Variable mais ils sont sur notre drive c2 :)

2023-06-11 13:30 UTC, YannickPassa commented on dags/nps_pilotage.py
> +        engine = create_engine(url)
Ok, je le rajouterai dans `dags/common/db.py`

2023-06-12 08:40 UTC, dejafait reviewed
Quelques pinaillages en passant.

2023-06-12 08:40 UTC, dejafait commented on dags/common/db.py
> +    return "postgresql://" + user + ":" + password + "@" + host + ":" + port + "/" + database
Les f string c'est plus élégant : `f"postgresql://{user}:{password}@{host}:{port}/{database}"`

2023-06-12 08:40 UTC, dejafait commented on dags/common/dates.py
> +    return start_of_previous_week, end_of_previous_week
Wow ce que retourne cette fonction n'est pas du tout ce que dit son nom, c'est confusant. Je propose `get_previous_week` ou `get_start_and_end_of_previous_week` ou `get_previous_week_range`.

2023-06-12 08:40 UTC, dejafait commented on dags/nps_pilotage.py
> +        # I need to create these columns and fill them with NaN
`I` dans le code ? Comment sait-on qui est `I` ? On doit aller faire un `git blame` ? Soit tu mets ton nom/pseudo, soit tu mets `We`. Ou encore `These columns need to be created` sans pronom.

2023-06-12 08:50 UTC, YannickPassa commented on dags/common/dates.py
> +    return start_of_previous_week, end_of_previous_week
Oups en effet

2023-06-12 08:57 UTC, vperron commented on dags/common/dates.py
> +    return start_of_previous_week, end_of_previous_week
Il faut faire 3 fonctions.

2023-06-12 08:58 UTC, vperron commented on dags/common/dates.py
> +    return start_of_previous_week, end_of_previous_week
Chacune retournant exactement une valeur, et ces fonctions peuvent s'appeler entre elles pour rester DRY (dont repeat yourself)

2023-06-12 09:00 UTC, vperron commented on dags/common/db.py
> +    return "postgresql://" + user + ":" + password + "@" + host + ":" + port + "/" + database
Ta fonction devrait retourner `sqlalchemy.create_engine(la_string)` pas juste une string, ça sera plus efficace. 

Et utilise-la aussi du coup dans l'autre DAG qui utilise ça.

2023-06-13 06:50 UTC, YannickPassa commented on dags/common/dates.py
> +    return start_of_previous_week, end_of_previous_week
En gros tu anticipes une future utilisation de` start_of_the_week `ailleurs et donc faudrait en faire une fonction ?

2023-06-14 06:43 UTC, closed without merging