mise à dispo des données de visites pour les campagnes matomo du c0
gip-inclusion/pilotage-airflow pull request #84
Opened 2023-07-05 16:16 UTC by laurinehu

**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Extraction-MATOMO-des-campagnes-pour-le-c0-7e12a0d84e944cd08acf40252ba2a304?pvs=4

### Pourquoi ?

mise à dispo des données de visites pour les campagnes matomo du c0

### Checks

- [x] J'ai lancé le modèle ou seed sur un dump local (si pertinent)
- [] J'ai ajouté des tests à mon code Python, ou des assertions DBT sur le modèle SQL
- [x] J'ai documenté ce modèle voire certains de ses champs (usage métier, tableau de bord, etc)

2023-07-05 16:38 UTC, laurinehu commented
No comprendo pourquoi la CI râle sur les imports alors que j'ai fait pareil que dans les autres scripts ..

2023-07-05 18:28 UTC, YannickPassa commented
>No comprendo pourquoi la CI râle sur les imports alors que j'ai fait pareil que dans les autres scripts ..

T'as bien téléchargé tous les linter ?

2023-07-07 09:20 UTC, vperron commented
Tu t'en sors avec le rebase + MAJ + coup de main + nettoyage ?

2023-07-07 09:55 UTC, laurinehu commented
> Tu t'en sors avec le rebase + MAJ + coup de main + nettoyage ?

oui, cependant j'arrive pas à reproduire les erreurs de lint de la ci en local :))) incompréhensible.

2023-07-19 08:53 UTC, vperron reviewed
Bravo pour ta ténacité et ton envie de te lancer dans un DAG <3

Sur la structure c'est top et je pense que ça marche dans les grandes lignes. 

J'ai mis beaucoup de conseils et de bonnes pratiques Python que clairement tu ne peux pas deviner; mais normalement après ça tu seras déjà beaucoup plus à l'aise, ça sera plus lisible et je pense qu'on aura moins de bugs en puissance !

Ca me fait bien plaisir que tu te lances là dedans !

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +import pandas as pd
spécificité Airflow: il vaut mieux importer les trucs lourds au dernier moment, donc dans la fonction qui va utiliser pandas si possible.

https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +            "https://matomo.inclusion.beta.gouv.fr/index.php"
bonne pratique Python: on extrait les valeurs de ce type (configurables) dans une variable extérieure que l'on peut configurer.

Cela permet de ne pas taper sur la prod durant tes tests locaux si elle n'est pas définie par exemple.

Ici je conseillerais de créer une variable Airflow, par exemple en la nommant `MATOMO_BASE_URL`.

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +            "&segment=referrerType==campaign;referrerName==c0"
c0 ?

Je pense que ça vaudrait le coup d'expliquer d'où vient cette valeur si un jour on veut/doit la changer avec un petit commentaire.

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +            "&idSite={}"
idéalement utiliser plutôt le format de chaîne Python 3+ : `f"&idSite={idsite}` plutôt que `.format()` .

C'est plus lisible (pas besoin d'aller 10 lignes plus bas pour voir ce qu'on va y mettre), plus concis et plus recommandé par les bonnes pratiques Python et les linters.

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +            "&date=2023-05-01"
on veut vraiment que ce soit toujours le mois de Mai 2023 ?

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +def get_visits_per_campaign(tok):
pour le nom de la fonction: (tu ne fais pas encore bcp de code donc je donne un max de bonnes pratiques, ça va venir très vite t'inquiète !)
- le `get` est un peu inutile, c'est un peu beateau dans un nommage, on le retire souvent au profit de quelque chose de plus précis. par exemple ici tu as deux fonction en `get_`, une va chercher sur une API l'autre pas.
- `tok` est un diminutif qui n'est pas nécessaire, c'est toujours mieux d'être explicite on ne cherche plus de nos jours à économiser des caractères à taper. `token` est très bien.
- c'est pas mal de documenter ce que va faire la fonction directement via son nom: par exemple `fetch_campaign_traffic_dataframe(token)` : on voit ce que ça fait en gros, et on a meme une info sur le type retourné (une dataframe)

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +    return infos
C'est une toute petite fonction interne ça, je pense que tu pourrais la mettre dans la fonction du dessous.

Ici elle induit un peu en erreur car on pense que comme l'autre elle va aller chercher sur l'API (elles sont toutes les deux des `get_xxx` alors que non. Et elle n'est utilisée que à l'intérieur de l'autre fonction et sera probablement pas réutilisée ailleurs, donc je dirais de juste l'y inclure.

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +        "visiteur": json_visit["visitorId"],
remarque: on perd de l'info en passant d'un `visitor_id` à `visiteur`, on ne voit plus directement que c'est un ID au lieu d'un nom, prénom, adresse mail par exemple. On peut mettre `id_visiteur` par exemple ?

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +    """
ce commentaire est un peu inutile, à retirer. Je pense que je l'ai déjà dit ailleurs mais si le commentaire décrit "ce que fait" la fonction, il est inutile et le code "gagne", c'est lui qui porte la vérité.

Le code va évoluer et le commentaire rarement, il va donc "moisir".

On ne met des commentaires que lorsque ils expliquent le "pourquoi" par exemple, ou documentent un truc compliqué que le code ne permet pas de voir (historique d'une décision par exemple)

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +    return dtf
au final, je te conseille de faire une fonction qui prend en paramètre un ID de site et retourne les infos en JSON, et de faire dans ton DAG la boucle qui agrège tout dans la même dataframe.

2023-07-19 08:53 UTC, vperron commented on dags/suivi_visites_campagnes_c0.py
> +    schedule_interval="@weekly",
alors que on prend des resultats mensuels ? cf le monthly dans ton appel API.

2023-07-19 08:53 UTC, vperron commented on dags/common/matomo.py
> +            "&method=Live.getLastVisitsDetails"
ah oui, on va chercher dans `getLastVisistsDetails` carrément ? Pourquoi pas, mais c'est un peu vener, c'est le détail le plus fon possible. Mais pourquoi pas ! Pas de besoin de changement je suis juste étonné.

2023-07-19 08:53 UTC, vperron commented on dags/suivi_visites_campagnes_c0.py
> +        """
mieux vaut faire un bon nom de task que de mettre un commentaire !

2023-07-19 08:53 UTC, vperron commented on dags/suivi_visites_campagnes_c0.py
> +        tok = Variable.get("TOKEN_MATOMO_GIP")
Yoda: je dirais pour suivre la meme regle de nommage que dans les autres variables de dire à l'inverse:
- d'abord la catégorie
- puis quoi en particulier
Ici, `GIP_MATOMO_TOKEN` . Comme ça derrière avec le meme préfixe tu peux faire `GIP_MATOMO_URL` pour son adresse.

2023-07-19 08:53 UTC, vperron commented on dags/suivi_visites_campagnes_c0.py
> +        print("saved")
c'est en trop ça :)

2023-07-19 10:37 UTC, laurinehu commented on dags/common/matomo.py
> +            "&segment=referrerType==campaign;referrerName==c0"
c'est par ce referrerName que sont idnetifiées les campagnes du c0 que je dois récupérer, ok pour le comm !

2023-07-19 10:37 UTC, laurinehu commented on dags/common/matomo.py
> +            "&idSite={}"
ok !

2023-07-19 10:37 UTC, laurinehu commented on dags/common/matomo.py
> +            "&date=2023-05-01"
oula non, ça semble être une erreur, merci

2023-07-19 10:38 UTC, laurinehu commented on dags/common/matomo.py
> +            "&method=Live.getLastVisitsDetails"
y'a peut être une meilleure méthode que je n'ai pas trouvée mmmh

2023-07-19 10:39 UTC, laurinehu commented on dags/suivi_visites_campagnes_c0.py
> +        """
si mes souvenirs sont bons c'est le linter qui râlait que je ne mette pas de docstring ! ton commentaire suggèrait que j'enlève le comm ou que je modifie le nom de task ou les deux ?

2023-07-19 10:39 UTC, laurinehu commented on dags/suivi_visites_campagnes_c0.py
> +        tok = Variable.get("TOKEN_MATOMO_GIP")
ok !

2023-07-19 10:39 UTC, laurinehu commented on dags/suivi_visites_campagnes_c0.py
> +        print("saved")
oopsi thx

2023-07-19 11:57 UTC, vperron commented on dags/suivi_visites_campagnes_c0.py
> +        """
Les deux !

2023-07-19 12:53 UTC, laurinehu commented on dags/common/matomo.py
> +import pandas as pd
ha bah le linter me mets d'office pandas en premier 🤨 à cause de l'ordre alphabétique j'imagine ? 
moyen de changer ça ds la config ?

2023-07-19 13:08 UTC, vperron commented on dags/common/matomo.py
> +import pandas as pd
Je ne dis pas "en premier en haut de fichier", je disais "dans la fonction qui l'utilise". Décalé de 4 espaces du coup.

D'ailleur si tu suis mes recommandations (toutes celles de la PR) tu n'auras meme plus besoin de l'importer dans `dags.common` mais uniquement dans le DAG final, et pour cela regarde les autres DAGs comment ils importent pandas : en plein milieu.

2023-07-19 13:15 UTC, laurinehu commented on dags/common/matomo.py
> +import pandas as pd
ohhhh sorry, très clair

2023-07-19 14:20 UTC, laurinehu commented on dags/suivi_visites_campagnes_c0.py
> +        """
ok pour le renommage mais je confirme que le linter râle si je ne lui mets pas de docstring 🤨

2023-07-19 15:12 UTC, YannickPassa commented on dbt/models/marts/etp_par_genre.sql
attention y a un souci ici, cette table est finalement devenue `etp_par_salarie`. Tu as du récupérer un commit qui trainait et ça ne t'indique pas de conflit car ça n'a pas le même nom

2023-07-19 15:13 UTC, YannickPassa commented on dbt/models/marts/properties.yml
pareil, nom de table pas bon ici

2023-07-19 15:43 UTC, laurinehu commented
BON, ça m'a l'air bueno, mais need double check

2023-07-20 08:10 UTC, YannickPassa requested changes
Il y a toujours des conflits à résoudre !

2023-07-20 08:10 UTC, YannickPassa commented on dbt/models/marts/etp_par_genre.sql
Il y a toujours un problème de conflits, ce fichier n'est pas supposé exister :(

2023-07-20 08:10 UTC, YannickPassa commented on dbt/models/marts/properties.yml
> +  - name: etp_par_genre
C'est toujours là alors que ça devrait pas exister non plus :(

2023-07-20 08:53 UTC, YannickPassa approved these changes
Ok pour moi !

2023-07-24 13:46 UTC, closed without merging